package com.bumble.puzzyx.entries

val fakeTwitterHandles = listOf(
    "@tweetNinja",
    "@socialWanderer",
    "@codeGeek",
    "@pixelPioneer",
    "@techCraftsman",
    "@byteBender",
    "@stellarTweeter",
    "@waveSurfer",
    "@dreamyDev",
    "@cyberPioneer",
    "@maverickCoder",
    "@gitGuru",
    "@byteBlaze",
    "@bugHuntingHero",
    "@artSculptor",
    "@algoExplorer",
    "@whizKidCoder",
    "@pixelPirate",
    "@juggleTheCode",
    "@scribeData",
    "@cyberNomad",
    "@alchemyCoder",
    "@safariByte",
    "@trailblazingTech",
    "@voyagingDev"
)

val fakeGitHubUserNames = listOf(
    "codeNinja",
    "pixelPusher",
    "techWanderlust",
    "dataGeek",
    "codeCraftsman",
    "byteBender",
    "stellarCoder",
    "codeWaveSurfer",
    "devDreamer",
    "cyberPioneer",
    "codeMaverick",
    "gitGuru",
    "byteBlaze",
    "bugHuntingHero",
    "techSculptor",
    "algoExplorer",
    "codeWhizKid",
    "pixelPirate",
    "codeJuggler",
    "dataScribe",
    "cyberNomad",
    "codeAlchemy",
    "byteSafari",
    "techTrailblazer",
    "devVoyager"
)

val fakeMessages = listOf(
    "Having a blast at the conference!",
    "Keynote was inspiring",
    "Shoutout to the organizers for an amazing lineup!",
    "Learning, networking, and free coffee – conference life is good!",
    "Let's connect! Find me at the networking session!",
    "L77tc0der was here",
    "Mind blown by the innovative ideas shared today.",
    "Great to see old friends and make new ones!",
    "Who's up for a post-conference karaoke session tonight?",
    "Loving the energy and enthusiasm of this crowd!",
    "Kudos to the speakers for keeping us engaged all day.",
    "Highlight of the day: the interactive workshop on Appyx.",
    "Impressed by the cool tech showcased in the exhibition hall!",
    "Taking copious notes – my brain might explode!",
    "Attending from NYC – making my hometown proud!",
    "Let's trend this conference on social media – use #AwesomeConf!",
    "First-time attendee and already hooked on these insights.",
    "Who's in for the spontaneous breakout discussion in the lobby?",
    "Can't believe how fast the day flew by – time flies when you're learning!",
    "Bravo to the panelists for the thought-provoking debate.",
    "Coffee break saved my brain from information overload!",
    "Feeling grateful for the opportunity to be here among industry giants.",
    "Eager to implement these strategies as soon as I'm back!",
    "Don't be shy – share your most mind-blowing takeaway!"
)
