package com.bumble.livemosaic.ui

import androidx.compose.ui.graphics.Color

val appyx_yellow1 = Color(0xFFFFC629)
val appyx_yellow2 = Color(0xFFFFE54A)
val appyx_dark = Color(0xFF1F2126)
val appyx_bright = Color(0xFFFFFFFF)

val md_theme_dark_primary = Color(0xFFF6BE1F)
val md_theme_dark_onPrimary = Color(0xFF3F2E00)
val md_theme_dark_primaryContainer = Color(0xFF5A4300)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDF9A)
val md_theme_dark_secondary = Color(0xFFD7C4A0)
val md_theme_dark_onSecondary = Color(0xFF3A2F15)
val md_theme_dark_secondaryContainer = Color(0xFF52452A)
val md_theme_dark_onSecondaryContainer = Color(0xFFF4E0BB)
val md_theme_dark_tertiary = Color(0xFFAFCFAA)
val md_theme_dark_onTertiary = Color(0xFF1C361D)
val md_theme_dark_tertiaryContainer = Color(0xFF324D31)
val md_theme_dark_onTertiaryContainer = Color(0xFFCBEBC5)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1E1B16)
val md_theme_dark_onBackground = Color(0xFFE9E1D9)
val md_theme_dark_surface = Color(0xFF1E1B16)
val md_theme_dark_onSurface = Color(0xFFE9E1D9)
val md_theme_dark_surfaceVariant = Color(0xFF4D4639)
val md_theme_dark_onSurfaceVariant = Color(0xFFD0C5B4)
val md_theme_dark_outline = Color(0xFF999080)
val md_theme_dark_inverseOnSurface = Color(0xFF1E1B16)
val md_theme_dark_inverseSurface = Color(0xFFE9E1D9)
val md_theme_dark_inversePrimary = Color(0xFF785A00)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFF6BE1F)
val md_theme_dark_outlineVariant = Color(0xFF4D4639)
val md_theme_dark_scrim = Color(0xFF000000)
